### ISSUE TITLE
Typo in `clear-afred-query-history`

### ISSUE THREAD

**Issue by chrismessina** [mr-pennyworth/alfred-history-search#1]
`clear-afred-query-history` should be `clear-alfred-query-history`

![CleanShot 2021-06-19 at 14 46 07@2x](https://user-images.githubusercontent.com/22610/122656177-1ca09c80-d10d-11eb-8c14-d1ba704c60ea.png)

**Comment by mr-pennyworth** [comment]
Thanks for reporting! :)
